### ISSUE TITLE
Issue with yield self within a ternary operator

### ISSUE THREAD

**Issue by gbp** [samphippen/rubyfmt#227]
After your NoRuKo talk I tested against our codebase and this issue was immediately obvious.

* Ruby version: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
* Rubyfmt git sha: 3435618

## Input file

```ruby
def foo(&block)
  block_given? ? yield(self) : self
end
```

## Rubyfmt's output

```
def foo(&block)
  block_given? ? yield self : self
end
```

## This breaks because

Output is syntactically incorrect, Ruby errors with `syntax error, unexpected self, expecting ':'`.

**Comment by kaoru** [comment]
Bump - this is the only bug we're seeing on our few thousand files at CharlieHR 😄 

@penelopezone I'd love to be able to submit a pull request for this bug, ideally with a test. Could you point me in the direction of the files I should start from? It looks like I'd want to add a `fixtures/small/yield_with_ternery_hook.rb` and then update something in `librubyfmt/src/format.rs`? How do I actually run the tests?

**Comment by fables-tales** [comment]
Hi there! Generally, I would ask you to please not bump issues for bumping's sake. I track them all and I work through them in the order that makes sense to me. I'll get to it eventually, I promise :)

As for working on it: I would suggest adding a new fixture, and running the tests with `./script/tests/text_fixtures.sh`. You will need both _expected and _actual files. In order to actually fix it you'll probably need to add a formatting context: https://github.com/penelopezone/rubyfmt/blob/trunk/librubyfmt/src/parser_state.rs#L15 called "IfOp' (IfOp is what ruby calls a ternary) and then add that call here: https://github.com/penelopezone/rubyfmt/blob/trunk/librubyfmt/src/format.rs#L2429. Once you've done that, checking the current formatting context: https://github.com/penelopezone/rubyfmt/blob/trunk/librubyfmt/src/parser_state.rs#L442 and forcing parens in a yield call: https://github.com/penelopezone/rubyfmt/blob/trunk/librubyfmt/src/format.rs#L2509 should work.

I hope that helps.

**Comment by kaoru** [comment]
> Generally, I would ask you to please not bump issues for bumping's sake.

Ack, sorry Penelope! Thanks for letting me know, I won’t do it again.

> As for working on it: …

Amazing, I’ll give it a go 😄 Thanks for the tip about IfOp, I definitely would’ve been tripped up by that.
