### ISSUE TITLE
RFC: Consider not doing newline/trailing comma for single entry collections

### ISSUE THREAD

**Issue by samphippen** [samphippen/rubyfmt#42]
@searls @tenderlove @sgrif @cflipse @derekprior 

currently rubyfmt will reformat:

```ruby
[a]
```

as

```ruby
[
  a,
]
```

(on the basis that newlines and trailing commas reduce git churn). My feeling is that this is so unergonomic to ruby users that it would make Rubyfmt unusable, and that the most likely use of a single entry array is unlikely to cause it to churn to contain multiple entries. Please feel free to discuss here, and give a 👍  or 👎  as an up/down vote on instead not newline breaking single entry arrays.

**Comment by sgrif** [comment]
I think this can go farther than single element arrays. IMO `[1, 2, 3]` should stay on a single line as well. Ultimately this sort of thing seems like it should be based on a length budget. If all expressions in an array will be formatted as a single line, and the length of the whole array is under some max length (either the global max line length or some smaller number specifically for this purpose), the array is kept as a single line

**Comment by samphippen** [comment]
@sgrif consider something like:

```ruby
def foo
  ops = [
    {create: tragedy_criterion},
    {create: placement_criterion},
  ]
end
```

One wouldn't go over 80 characters here, but I feel like line breaking there is the right thing to do. This collection is *screaming* that it's going to have more things added in the future.

**Comment by samphippen** [comment]
although I'd probably want

```ruby
ops = [
  {create: tragedy_critereon},
]
```
too. Maybe we break collections if they contain other collections, method calls with parens, or if they go over 80 chars?

**Comment by samphippen** [comment]
+@tiffanypeon

**Comment by searls** [comment]
I am with @sgrif in that I think breaking newlines aggressively in this way will be a turn-off, especially if the array or hash literal is pretty short. I'd be fine with arbitrarily stating some rule like "literals under 40 chars OR that would bring the line to over 80 chars get new-linified", though.

**Comment by samphippen** [comment]
@searls how do you feel about my cases above where we introspect content to come up with breaking rules?

**Comment by searls** [comment]
I feel the same about `[{a: 2}, {b: 3}]` as I do about `[:fizzle, :frazzle]`. I'd be mad if I wrote it as a one-liner and then a tool split it out

**Comment by searls** [comment]
I think the rule of thumb for me is that "if it'd be pretty natural to write it one way, the formatter should prefer that way", and the above case is perhaps debatable. I can see why this project is going to take more time to simmer down than Standard based on its need to weigh in on things like this.

**Comment by samphippen** [comment]
Does rubyfmt need to allow you to both break manually, and non break manually in those cases?

e.g.

user writes:

```ruby
[a, b]
```

is preserved

user writes:
```ruby
[
  a,
  b,
]
```

also preserved?

**Comment by samphippen** [comment]
> I think the rule of thumb for me is that "if it'd be pretty natural to write it one way, the formatter should prefer that way", and the above case is perhaps debatable. I can see why this project is going to take more time to simmer down than Standard based on its need to weigh in on things like this.

Welcome to "caremad club"

**Comment by sgrif** [comment]
"If user writes x is it preserved?"

Personally I think the answer to that should be no whenever possible. Unless reformatting what the user wrote changes semantics (e.g. re-ordering method definitions), format of the input should never affect the format of the output.

re: https://github.com/samphippen/rubyfmt/issues/42#issuecomment-472598553

That's why I suggested the length budget here should potentially be shorter, or perhaps based on the complexity of the input. At the end of the day there will always be some cases that are sub-optimal. As an arbitrary example, Diesel had this:

```
let expected_bytes = vec![
    16, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 1,
];
```

which got each element put on its own line which is one of those pathological cases that no formatting tool will optimize for readability, but at the end of the day it's fine if it's sub-optimal in a handful of cases. Worst case you can always add the ability to tell it to ignore a single expression/block/file

**Comment by samphippen** [comment]
+@valeriecodes

**Comment by cflipse** [comment]
Small arrays that can easily fit on one line should probably stay that way unless or until I break 80 characters, or I explicitly start wrapping them.  I'm okay with nested hashes breaking lines; I think that's probably better because it helps to line up the hash entries and make them less noisy.

In general, I tend to value vertical compactness more than statement fragments on their own line; it's a question of optimizing for git churn vs. optimizing for seeing more context on the screen, and the answer is going to depend on situtation

**Comment by tenderlove** [comment]
I agree with @sgrif and @cflipse. Only break at 80 characters (where 80 includes the current indentation).

**Comment by samphippen** [comment]
I implemented this specific rule because it felt right, will spend more attention on collections soon.
