### ISSUE TITLE
make rubyfmt wrap at 80 chars

### ISSUE THREAD

**Issue by samphippen** [samphippen/rubyfmt#45]
Rubyfmt currently doesn't implement wrapping, however my feeling is that 80 chars is the right place to wrap, and so Rubyfmt needs to implement that.

**Comment by searls** [comment]
I'm just going to go on the record with my opinion that this is going to be too constraining for a lot of people and will either hamper adoption or lead to a lot of complaining. The problem is that 100, or 120, or some higher number won't satisfy anyone either.

I've ben chewing on this, and I wonder if — since rubyfmt is a computer and computers understand complex algorithms— there is a more complex decision tree that the tool could walk to determine when to wrap and at which points. 

For instance, many people generally like 80c's, except when they don't. When don't they? We should dig in and see if we can't codify exceptions clearly. Maybe:

1. When a large data structure is being defined and in the interest of compactness, each line is an array literal containing hashes, and they each take up 90 characters, but implementing this wrapping rule and other newline rules would take the overall length of the file from 100 to 400 lines. The tool could theoretically detect that this would be a pretty drastic change and opt not to do anything in that case.

2. When a line is between 80 and 90 characters and breaking the newline will result in a not-at-all proportionate or unseemly 1-10 character second line that forces the reader to scan all the way to the left to finish reading it. The lack of balance between the two lines _looks_ to the human eye as imbalanced/ugly, but I think we could implement a rule like the ratio in resulting line length to detect that sorta imbalance and ignore it.

**Comment by localhostdotdev** [comment]
prettier does 80 characters and everyone seems fine with that

**Comment by searls** [comment]
@localhostdotdev I don't. It's expressly why I haven't adopted prettier

**Comment by samphippen** [comment]
+@valeriecodes

**Comment by cflipse** [comment]
Things to consider:

URLs tend to explode over the 80 character limit

Multi-line heredocs that are indented several levels -- if they're destined for terminal output, the artificial right boundary can look really disconcerting.

Actually, these are both instances of really big string literals ...

**Comment by valeriecodes** [comment]
I only care about line length when viewing on a screen or editor that doesn't soft-wrap, which most do or can be configured to do.
That said, I think that the beauty of an autoformatter is that it can do annoying things like separate a list into ~80 char chunks pretty easily.
I personally prefer 120 char lines as they still can easily fit in one line on modern monitors, but in the interest of consistency I think 80 chars + caveats, as @searls alluded to, makes sense.

Possible caveats:
For long lists or statements, bias toward even-ness (not having only a few characters on each line) rather than a strict 80-char upper limit.
Long strings that are still < 100 chars

**Comment by antoinelyset** [comment]
Just my 2cts but it seems to be a hard problem to solve without a good algorithm.

Prettier used this one for example : http://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf

**Comment by mwean** [comment]
We've gone with 120 and it's worked pretty well. Long, descriptive variable names and classes make 80 tough to follow.

**Comment by mikker** [comment]
I have no problem with 80 and actually like it. What usually breaks are, as mentioned, long strings, urls, long regexes.

Jus wanted to throw in a vote for 80.

**Comment by samphippen** [comment]
@searls how strongly do you feel like 80 is the wrong breakpoint? Like "I refuse to use this tool if we pick 80" or like "I could learn to live with it".

Same for 100

**Comment by localhostdotdev** [comment]
BTW prettier-ruby does 80 chars (configurable) (not strict) and works pretty well but generates quite a lot of edge cases.

**Comment by jeromedalbert** [comment]
My personal style with Ruby is way less than 80 characters, so I am fine with this proposal.

You can't please everyone, but again neither does Prettier. The age-old standard is 80.

**Comment by samphippen** [comment]
Changed my mind on this. I've been very carefully eyeballing all the ruby I've written for the past n days, and rubyfmt's gonna wrap at 100.

**Comment by jswright61** [comment]
@samphippen will 100 be configurable? The reason I ask is I'd like to second @mwean's earlier comment. I think enforcing short line lengths encourages shorter variable  and class names which makes it just a little harder to understand intent.

As @searls says there is not a number that will make _most_ people happy, forget about _all_. My preference is 120 - that's where GitHub (and many other sites) wrap lines.

In my opinion, any number that is not configurable will severely limit adoption.

**Comment by bquorning** [comment]
> In my opinion, any number that is not configurable will severely limit adoption.
 
I agree.

A simpler configuration option could be to just be able to turn the feature on or off.

**Comment by valeriecodes** [comment]
I think this gets to the question of whether there should be a limit at all. In some ways it would add more git churn, and there is a good deal of division on what the "right" character limit would be.
